#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Run with 'activate' argument!"
    exit
fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

cat > src/lib/cpmf/PMFMainHeaderConfig.hpp << EOF
#define PMF_VERSION         "6.${GITREVS}.${GITHASH}"
#define PMF_BUILDTIME       "${DATE}"
EOF

cat > src/lib/fpmf/common/pmf_ver.f90 << EOF
module pmf_ver
use pmf_sizes
use pmf_constants
implicit none
!-------------------------------------------------------------------------------
character(80),parameter   :: PMFLIBVER   = 'PMFLib 6.${GITREVS}.${GITHASH} (${DATE})'
!-------------------------------------------------------------------------------
end module pmf_ver
EOF

echo ""
echo "PMFLib Revision: 5.$GITREVS.$GITHASH ($DATE)"

