PMFLIB_SANDER_EXT=\
        -lfpmfdrv_sander -lfpmf \
        -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib/drivers \
        -lnetlib -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/netlib/1.0/lib \
        -lcprmfile -lfprmfile -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/prmfile/1.0/lib \
        -lflapackd -L/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/lapack/3.1.1/lib \
        -lfblasd -L/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/blas/netlib/lib \
        -lcpmf -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib \
        -lcsparse -L/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/csparse/2.2.1/lib \
        -lfscimafic -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/scimafic/1.0/lib \
        -lcscimafic -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/scimafic/1.0/lib \
        -lhipoly -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/hipoly/1.0/lib \
         \
        -Wl,-rpath=/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib/drivers:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/netlib/1.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/prmfile/1.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/lapack/3.1.1/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/blas/netlib/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/csparse/2.2.1/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/scimafic/1.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/hipoly/1.0/lib

PMFLIB_SANDER_MPI_EXT=\


PMFLIB_SANDER_XDYNBP_EXT=\


PMFLIB_PMEMD_EXT=\
        -lfpmfdrv_pmemd -lfpmf \
        -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib/drivers \
        -lnetlib -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/netlib/1.0/lib \
        -lcprmfile -lfprmfile -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/prmfile/1.0/lib \
        -lflapackd -L/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/lapack/3.1.1/lib \
        -lfblasd -L/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/blas/netlib/lib \
        -lcpmf -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib \
        -lcsparse -L/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/csparse/2.2.1/lib \
        -lfscimafic -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/scimafic/1.0/lib \
        -lcscimafic -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/scimafic/1.0/lib \
        -lhipoly -L/scratch/kulhanek/Development/github/builds/pmflib-build/projects/hipoly/1.0/lib \
         \
        -Wl,-rpath=/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib/drivers:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/netlib/1.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/prmfile/1.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/lapack/3.1.1/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/blas/netlib/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/pmflib/4.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/thirdparty/csparse/2.2.1/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/scimafic/1.0/lib:/scratch/kulhanek/Development/github/builds/pmflib-build/projects/hipoly/1.0/lib

PMFLIB_PMEMD_MPI_EXT=\


