PMFLIB_CPMD_EXT=\
        -lfpmfdrv_cpmd -lfpmf \
        -L/scratch/kulhanek/Development/linux/projects/pmflib/4.0/lib \
        -L/scratch/kulhanek/Development/linux/projects/pmflib/4.0/lib/drivers \
        -lcpmf -L/scratch/kulhanek/Development/linux/projects/pmflib/4.0/lib \
        -lfprmfile -L/scratch/kulhanek/Development/linux/projects/prmfile/1.0/lib \
        -lcprmfile -L/scratch/kulhanek/Development/linux/projects/prmfile/1.0/lib \
        -lnetlib -L/scratch/kulhanek/Development/linux/projects/netlib/1.0/lib \
        -lcsparse -L/scratch/kulhanek/Development/linux/thirdparty/csparse/2.2.1/lib \
        -lfscimafic -L/scratch/kulhanek/Development/linux/projects/scimafic/1.0/lib \
        -lcscimafic -L/scratch/kulhanek/Development/linux/projects/scimafic/1.0/lib \
        -lhipoly -L/scratch/kulhanek/Development/linux/projects/hipoly/1.0/lib \
         \
        -Wl,-rpath=/scratch/kulhanek/Development/linux/projects/pmflib/4.0/lib:/scratch/kulhanek/Development/linux/projects/pmflib/4.0/lib/drivers:/scratch/kulhanek/Development/linux/projects/netlib/1.0/lib:/scratch/kulhanek/Development/linux/projects/prmfile/1.0/lib:/scratch/kulhanek/Development/linux/projects/pmflib/4.0/lib:/scratch/kulhanek/Development/linux/thirdparty/csparse/2.2.1/lib:/scratch/kulhanek/Development/linux/projects/scimafic/1.0/lib:/scratch/kulhanek/Development/linux/projects/hipoly/1.0/lib

PMFLIB_CPMD_XDYNBP_EXT=\


