.TH abf-derivatives 1 "2008" "PMFLib" "PMFLib - Library Supporting Potential of Mean Force Calculations"

.\"-----------------------------------------------------------------------------
.SH NAME
abf-derivatives

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
abf-derivatives [OPTIONS] [--] accuname dname

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints selected derivatives from ABF accumulator.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B accuname
.RS
file name of ABF accumulator file
.RE

.B dname
.RS
file name with derivatives
.RE

.\"-----------------------------------------------------------------------------
.SH OPTIONS
.B -l, --limit=LIMIT
.RS
only bins with the number of samples grater than or equal to LIMIT will be printed
.RE

.B -i, --item=ITEM
.RS
determine which ITEM should be printed
.RE

.B -g, --group=GROUP
.RS
determines which GROUP will be printed, zero and minus one have special meaning, zero indicates ABF free energy derivatives and minus one potential energy derivatives
.RE

.B -e, --errors
.RS
print the errors of derivatives instead of derivatives
.RE

.B --nognuplot
.RS
do not print delimiters between records
.RE

.B --noheader
.RS
do not print header to output file
.RE

.B --fx=FORMAT
.RS
output FORMAT of coordinate values
.RE

.B --fe=FORMAT
.RS
output FORMAT of samples
.RE

.B -v, --verbose
.RS
increase output verbosity
.RE

.B --version
.RS
output version information and exit
.RE

.B -h, --help
.RS
display this help and exit
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
pmflib(1), abf-combine(1), abf-integrate(1), abf-samples(1), abf-trajectory(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2009 Petr Kulhanek (NCBR)
.br
Copyright (c) 2008 Petr Kulhanek (IE), Letif Mones (IE)
.br
Copyright (c) 2007 Petr Kulhanek (IE), Martin Petrek (NCBR), Letif Mones (IE)
.br
Copyright (c) 2006 Petr Kulhanek (NCBR), Martin Petrek (NCBR)
.br
Copyright (c) 2005 Petr Kulhanek (NCBR)

.P
.I Affilations:
.br
IE  : Institute of Enzymology, Hungarian Academy of Science, Hungary
.br
NCBR: National Centre for Biomolecular Research, Masaryk University, Czech Republic
