.TH abf-integrate 1 "2008" "PMFLib" "PMFLib - Library Supporting Potential of Mean Force Calculations"

.\"-----------------------------------------------------------------------------
.SH NAME
abf-integrate

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
abf-integrate [OPTIONS] [--] accuname fename

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Numericaly integrate data given by ABF calculation. The integration is performed by reverse finite difference method with order either 3 or 4.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B accuname
.RS
file name of ABF accumulator file
.RE

.B fename
.RS
file name with free energy result
.RE

.\"-----------------------------------------------------------------------------
.SH OPTIONS
.B -l, --limit=SAMPLES
.RS
only bins with number of samples greater than limit will be used for integration
.RE

.B -g, --group=GROUP
.RS
determines which GROUP will be integrated, zero and minus one have special meaning, zero indicates ABF free energy derivatives and minus one potential energy derivatives
.RE

.B --fdorder=ORDER
.RS
determines differenciation scheme. Currently implemented schemes use either three or four points.
.RE

.B -o, --offset=OFFSET
.RS
OFFSET is an integration constant
.RE

.B -p, --periodic
.RS
switch on periodicity for dihedral angle reaction coordinate
.RE

.B -e, --errors
.RS
integrate the errors of derivatives
.RE

.B --nognuplot
.RS
do not print delimiters between records
.RE

.B --printwithlimit
.RS
print only those numbers that were adequately sampled
.RE

.B --noheader
.RS
do not print header to output file
.RE

.B --fx=FORMAT
.RS
output FORMAT of CV values
.RE

.B --fe=FORMAT
.RS
output FORMAT of free energy
.RE

.B -v, --verbose
.RS
increase output verbosity
.RE

.B --version
.RS
output version information and exit
.RE

.B -h, --help
.RS
display this help and exit
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
pmflib(1), pmflib(1), abf-combine(1), abf-derivatives(1), abf-samples(1), abf-trajectory(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2009 Petr Kulhanek (NCBR)
.br
Copyright (c) 2008 Petr Kulhanek (IE), Letif Mones (IE)
.br
Copyright (c) 2007 Petr Kulhanek (IE), Martin Petrek (NCBR), Letif Mones (IE)
.br
Copyright (c) 2006 Petr Kulhanek (NCBR), Martin Petrek (NCBR)
.br
Copyright (c) 2005 Petr Kulhanek (NCBR)

.P
.I Affilations:
.br
IE  : Institute of Enzymology, Hungarian Academy of Science, Hungary
.br
NCBR: National Centre for Biomolecular Research, Masaryk University, Czech Republic
