.TH abf-admin 1 "2008" "PMFLib" "PMFLib - Library Supporting Potential of Mean Force Calculations"

.\"-----------------------------------------------------------------------------
.SH NAME
abf-admin

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
abf-admin [OPTIONS] [--] pmf://server[:port]/command

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Administration utility for multiple walker ABF method server.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B pmf://server[:port]/command
.RS
specifies fully qualified administration request. Trasport protocol pmf:// has to be always specified. It is followed by server parameter which could be either DNS name or IP address of server. Optional port parameter is port number used in a communication. Finally, the command is administration task, which can be one of the following:
.RS
.B info
.RS
prints information about registered clients
.RE
.B flush
.RS
saves accumulated ABF data on server side
.RE
.B get
.RS
gets accumulated ABF data and saves them locally
.RE
.B shutdown
.RS
stops server execution
.RE
.B errors
.RS
prints errors from server stack
.RE
.RE

.\"-----------------------------------------------------------------------------
.SH OPTIONS
.B -p, --password=FILE 
.RS
name of file containing server magic word, if not specified then password is read interactively
.RE

.B -o, --output=FILE
.RS
output file name for 'get' command
.RE

.B -v, --verbose
.RS
increase output verbosity
.RE

.B --version
.RS
output version information and exit
.RE

.B -h, --help
.RS
display this help and exit
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
pmflib(1), abf-server(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2009 Petr Kulhanek (NCBR)
.br
Copyright (c) 2008 Petr Kulhanek (IE), Letif Mones (IE)
.br
Copyright (c) 2007 Petr Kulhanek (IE), Martin Petrek (NCBR), Letif Mones (IE)
.br
Copyright (c) 2006 Petr Kulhanek (NCBR), Martin Petrek (NCBR)
.br
Copyright (c) 2005 Petr Kulhanek (NCBR)

.P
.I Affilations:
.br
IE  : Institute of Enzymology, Hungarian Academy of Science, Hungary
.br
NCBR: National Centre for Biomolecular Research, Masaryk University, Czech Republic
