.TH mtd-server 1 "2008" "PMFLib" "PMFLib - Library Supporting Potential of Mean Force Calculations"

.\"-----------------------------------------------------------------------------
.SH NAME
mtd-server

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
mtd-server [OPTIONS] [--] control

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
mtd-server is multiple walker metadynamics server.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B control
.RS
name of control file
.RE

.\"-----------------------------------------------------------------------------
.SH OPTIONS
.B --donotshutdown
.RS
do not shutdown automatically when all clients are unregistered
.RE

.B -v, --verbose
.RS
increase output verbosity
.RE

.B --version
.RS
output version information and exit
.RE

.B -h, --help
.RS
display this help and exit
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
pmflib(1), mtd-admin(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2009 Petr Kulhanek (NCBR)
.br
Copyright (c) 2008 Petr Kulhanek (IE), Letif Mones (IE)
.br
Copyright (c) 2007 Petr Kulhanek (IE), Martin Petrek (NCBR), Letif Mones (IE)
.br
Copyright (c) 2006 Petr Kulhanek (NCBR), Martin Petrek (NCBR)
.br
Copyright (c) 2005 Petr Kulhanek (NCBR)

.P
.I Affilations:
.br
IE  : Institute of Enzymology, Hungarian Academy of Science, Hungary
.br
NCBR: National Centre for Biomolecular Research, Masaryk University, Czech Republic
