.TH mtd-energy 1 "2008" "PMFLib" "PMFLib - Library Supporting Potential of Mean Force Calculations"

.\"-----------------------------------------------------------------------------
.SH NAME
mtd-energy

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
mtd-energy [OPTIONS] [--] input output

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Calculate the free energy surface from given metadynamics restart file.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B input
.RS
input data file or - for data taken from standard input
.RE

.B output
.RS
output data file or - for data written to standard output
.RE

.\"-----------------------------------------------------------------------------
.SH OPTIONS
.B -t, --time=TIME
.RS
TIME specifies metadynamics time used in energy calculation
.RE

.B --offset=REAL
.RS
determine position of global minima
.RE

.B --smooth=SMOOTH
.RS
calculate energy surface average from time SMOOTH to TIME
.RE

.B --nognuplot
.RS
do not print delimiters between records
.RE

.B --noheader
.RS
do not print header to output file
.RE

.B --fx=FORMAT
.RS
output FORMAT of CV values
.RE

.B --fe=FORMAT
.RS
output FORMAT of free energy
.RE

.B -v, --verbose
.RS
increase output verbosity
.RE

.B --version
.RS
output version information and exit
.RE

.B -h, --help
.RS
display this help and exit
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
pmflib(1), abf-integrate(1), bm-integrate(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2009 Petr Kulhanek (NCBR)
.br
Copyright (c) 2008 Petr Kulhanek (IE), Letif Mones (IE)
.br
Copyright (c) 2007 Petr Kulhanek (IE), Martin Petrek (NCBR), Letif Mones (IE)
.br
Copyright (c) 2006 Petr Kulhanek (NCBR), Martin Petrek (NCBR)
.br
Copyright (c) 2005 Petr Kulhanek (NCBR)

.P
.I Affilations:
.br
IE  : Institute of Enzymology, Hungarian Academy of Science, Hungary
.br
NCBR: National Centre for Biomolecular Research, Masaryk University, Czech Republic
