.TH pmflib 1 "2008" "PMFLib" "PMFLib - Library Supporting Potential of Mean Force Calculations"

.\"-----------------------------------------------------------------------------
.SH NAME
pmflib

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
PMFLib - Library Supporting Potential of Mean Force Calculations

.\"-----------------------------------------------------------------------------
.SH SEE ALSO (Adaptive Biasing Method)
abf-admin(1), abf-combine(1), abf-derivatives(1), abf-integrate(1), abf-samples(1), abf-server(1), abf-trajectory(1)

.\"-----------------------------------------------------------------------------
.SH SEE ALSO (Blue Moon - Constrained Dynamics)
bm-integrate(1)

.\"-----------------------------------------------------------------------------
.SH SEE ALSO (Metadynamics)
bm-admin(1), mtd-energy(1), mtd-server(1)

.\"-----------------------------------------------------------------------------
.SH SEE ALSO (Umbrella Sampling - Restrained Dynamics)
um-samples(1)

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
pmflib(1), test-cvs(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2009 Petr Kulhanek (NCBR)
.br
Copyright (c) 2008 Petr Kulhanek (IE), Letif Mones (IE)
.br
Copyright (c) 2007 Petr Kulhanek (IE), Martin Petrek (NCBR), Letif Mones (IE)
.br
Copyright (c) 2006 Petr Kulhanek (NCBR), Martin Petrek (NCBR)
.br
Copyright (c) 2005 Petr Kulhanek (NCBR)

.P
.I Affilations:
.br
IE  : Institute of Enzymology, Hungarian Academy of Science, Hungary
.br
NCBR: National Centre for Biomolecular Research, Masaryk University, Czech Republic
